@ApiHost = http://localhost:8080
@healthCheckHost = http://localhost:8080

GET {{ApiHost}}

###

GET {{ApiHost}}/products/e6250604-b49e-4a9d-b29a-6f04694be350

###

POST {{ApiHost}}/products
Content-Type: application/json

{
    "name": "Book",
    "Quantity": 343
}

###

PUT {{ApiHost}}/products/e6250604-b49e-4a9d-b29a-6f04694be351
Content-Type: application/json

{
    "name": "Book",
    "Quantity": 31
}
###

DELETE {{ApiHost}}/products/84d1e21d-595b-466b-bec2-c9f84ab5341b


### Health Checks - root endpoint
GET {{healthCheckHost}}

### Health Check - alive endpoint
GET {{healthCheckHost}}/alive

### Health Check - readiness endpoint
GET {{healthCheckHost}}/ready

### Health Check - status endpoint
GET {{healthCheckHost}}/status
